// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtYMBE7Ly2a6Dz0PLBm4BSXQT4Pul6jRQ',
    appId: '1:364043557479:android:5f88b6630cc00c392c92c2',
    messagingSenderId: '364043557479',
    projectId: 'cognicare-ai',
    storageBucket: 'cognicare-ai.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtYMBE7Ly2a6Dz0PLBm4BSXQT4Pul6jRQ',
    appId: '1:364043557479:web:5f88b6630cc00c392c92c2',
    messagingSenderId: '364043557479',
    projectId: 'cognicare-ai',
    authDomain: 'cognicare-ai.firebaseapp.com',
    storageBucket: 'cognicare-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtYMBE7Ly2a6Dz0PLBm4BSXQT4Pul6jRQ',
    appId: '1:364043557479:ios:5f88b6630cc00c392c92c2',
    messagingSenderId: '364043557479',
    projectId: 'cognicare-ai',
    storageBucket: 'cognicare-ai.firebasestorage.app',
    iosBundleId: 'com.example.cognicareAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtYMBE7Ly2a6Dz0PLBm4BSXQT4Pul6jRQ',
    appId: '1:364043557479:ios:5f88b6630cc00c392c92c2',
    messagingSenderId: '364043557479',
    projectId: 'cognicare-ai',
    storageBucket: 'cognicare-ai.firebasestorage.app',
    iosBundleId: 'com.example.cognicareAi',
  );
}
